PRO INVERTBACKGROUND

COMPILE_OPT IDL2

IF !P.COLOR EQ 0 THEN BEGIN
  !P.BACKGROUND = 0
  !P.COLOR      = !D.N_COLORS-1
ENDIF ELSE BEGIN
  !P.BACKGROUND = !D.N_COLORS-1
  !P.COLOR      = 0 
ENDELSE

END
